# Development environment configuration
version: 1.0
environment: development

# Database Configuration
database:
  engine: 'high_performance_db'
  storage:
    data_path: '/var/db/data'
    log_path: '/var/db/logs'
    max_data_size_gb: 100
    max_log_size_gb: 20
  compression:
    enabled: true
    algorithms:
      - 'lz4'
      - 'snappy'
  formats:
    row_store:
      enabled: true
    column_store:
      enabled: true
  caching:
    enabled: true
    strategies:
      - 'write_through'
      - 'write_back'
    eviction_policies:
      - 'lru'
      - 'lfu'
    cache_size_gb: 10

# Indexing Configuration
indexing:
  b_tree:
    enabled: true
    max_height: 4
  hash_index:
    enabled: true
    hash_function: 'murmurhash'
  trie_index:
    enabled: true
  full_text_search:
    enabled: true
  spatial_index:
    enabled: true
    types:
      - 'r_tree'

# Query Processor Configuration
query_processor:
  optimization_levels:
    - 0
    - 1
    - 2
  join_algorithms:
    - 'hash_join'
    - 'merge_join'
  planner:
    strategies:
      - 'rule_based'
      - 'cost_based'

# Transaction Management
transactions:
  isolation_levels:
    - 'read_committed'
    - 'repeatable_read'
    - 'serializable'
  concurrency_control:
    methods:
      - 'two_phase_locking'
      - 'timestamp_ordering'

# Networking Configuration
networking:
  protocols:
    - 'grpc'
    - 'http2'
  rpc_timeout_seconds: 30
  max_connections: 100
  load_balancing:
    strategies:
      - 'round_robin'
      - 'consistent_hashing'

# Distributed Systems Configuration
distributed:
  sharding:
    enabled: true
    strategies:
      - 'hash'
      - 'range'
  replication:
    enabled: true
    modes:
      - 'master_slave'
      - 'multi_master'
  consensus:
    algorithms:
      - 'raft'
      - 'paxos'

# Caching Configuration
cache:
  enabled: true
  cache_types:
    - 'local'
    - 'distributed'
  eviction_policies:
    - 'lru'
    - 'lfu'
  size_gb: 15

# Logging and Monitoring Configuration
logging:
  levels:
    - 'debug'
    - 'info'
    - 'warn'
    - 'error'
  log_path: '/var/log/db_dev.log'
monitoring:
  enabled: true
  metrics_collector:
    interval_seconds: 60
  alerting:
    enabled: true
    threshold:
      latency_ms: 500
      disk_space_percent: 80

# Security Configuration
security:
  authentication:
    methods:
      - 'oauth2'
    token_expiry_seconds: 3600
  encryption:
    at_rest: true
    in_transit: true
    algorithms:
      - 'aes-128'
      - 'aes-256'
  firewall:
    enabled: true
    allowed_ips:
      - '127.0.0.1'
      - '192.168.0.0/16'

# Developer-Specific Configurations
developer_tools:
  enabled: true
  admin_console:
    port: 8080
  hot_reload: true
  verbose_logging: true